volumes:
  nginx-shared-txs:
  nginx-shared-cfg:

x-healthcheck-db-template: &pghealthcheck
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 30s
    timeout: 30s
    retries: 3

x-healthcheck-redis-template: &redishealthcheck
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 30s
    timeout: 30s
    retries: 3

x-healthcheck-celery-template: &celeryhealthcheck
  healthcheck:
    test: ["CMD", "celery", "inspect", "ping"]
    interval: 30s
    timeout: 30s
    retries: 3

services:
  # Common nginx and database
  nginx:
    image: nginx:alpine
    ports:
      - "${REVERSE_PROXY_PORT}:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared-txs:/nginx-txs
      - nginx-shared-cfg:/nginx-cfg
    depends_on:
      - txs-web
      - cfg-web
      - cgw-web
      - events-web

  txs-db:
    image: postgres:14-alpine
    command: -c 'max_connections=250'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/txs-db:/var/lib/postgresql/data
    <<: *pghealthcheck

  cfg-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/cfg-db:/var/lib/postgresql/data
    <<: *pghealthcheck

  events-db:
    image: postgres:14-alpine
    ports:
      - target: 5432
        published: 5434
        host_ip: 0.0.0.0
        protocol: tcp
        mode: host
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/events-db:/var/lib/postgresql/data
    <<: *pghealthcheck

  # Safe Transaction Service
  txs-redis:
    image: redis:alpine
    <<: *redishealthcheck

  txs-rabbitmq:
    image: rabbitmq:alpine

  txs-worker-indexer: &txs-worker
    image: safeglobal/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    environment:
      - RUN_MIGRATIONS=1
      - WORKER_QUEUES=default,indexing
    command: docker/web/celery/worker/run.sh
    <<: *celeryhealthcheck

  txs-worker-contracts-tokens:
    <<: *txs-worker
    environment:
      - WORKER_QUEUES=contracts,tokens

  txs-worker-notifications-webhooks:
    <<: *txs-worker
    environment:
      - WORKER_QUEUES=notifications,webhooks

  txs-web:
    image: safeglobal/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    environment:
    working_dir: /app
    volumes:
      - nginx-shared-txs:/nginx
    command: docker/web/run_web.sh

  txs-scheduler:
    <<: *txs-worker
    command: docker/web/celery/scheduler/run.sh

  # Safe Config Service
  cfg-web:
    image: safeglobal/safe-config-service:${CFG_VERSION}
    tty: true
    env_file:
      - container_env_files/cfg.env
    environment:
      - CGW_AUTH_TOKEN=${AUTH_TOKEN}
    depends_on:
      cfg-db:
        condition: service_healthy

  # Safe Client Gateway
  cgw-redis:
    image: redis:alpine
    <<: *redishealthcheck

  cgw-web:
    image: alex-test-updated-nest
    env_file:
      - container_env_files/cgw.env
    environment:
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_TOKEN=${AUTH_TOKEN}
    depends_on:
      cgw-redis:
        condition: service_healthy

  ui:
    image: alex-test-updated-web
    env_file:
      - container_env_files/ui.env
    depends_on:
      - nginx
    expose:
      - 8080

  general-rabbitmq:
    image: rabbitmq:alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 15s

  events-web:
    image: safeglobal/safe-events-service:${EVENTS_VERSION}
    env_file:
      - container_env_files/events.env
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      events-db:
        condition: service_healthy
      general-rabbitmq:
        condition: service_healthy
